<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>20d491d6-90d3-4a4e-8371-968fdf9c36da</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'ChangeDataCaptureHub.Web(Development)' "/>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'ChangeDataCaptureHub.Web(Production)' "/>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'ChangeDataCaptureHub.Web(Testing)' "/>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Grpc.Tools" Version="2.81.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChangeDataCaptureHub.ExternalService\ChangeDataCaptureHub.ExternalService.csproj"/>
    <ProjectReference Include="..\ChangeDataCaptureHub.Model\ChangeDataCaptureHub.Model.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\ChangeDataCaptureHub.DataAccess\ChangeDataCaptureHub.DataAccess.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\ChangeDataCaptureHub.Business\ChangeDataCaptureHub.Business.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\ChangeDataCaptureHub.Api\ChangeDataCaptureHub.Api.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
</Project>
