<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChangeDataCaptureHub.Model\ChangeDataCaptureHub.Model.csproj"/>
    <ProjectReference Include="..\ChangeDataCaptureHub.Common\ChangeDataCaptureHub.Common.csproj"/>
    <ProjectReference Include="..\ChangeDataCaptureHub.DataAccess\ChangeDataCaptureHub.DataAccess.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="RabbitMQ\"/>
    <None Remove="RabbitMQ\EventProcessing\"/>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="RabbitMQ\EventProcessing\"/>
  </ItemGroup>
</Project>
