<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToDoListManager.Common\ToDoListManager.Common.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="RabbitMQService\"/>
    <Folder Include="RabbitMQService\Contracts\"/>
  </ItemGroup>
</Project>
