<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos/todolistmanager.proto" GrpcServices="Client"/>
  </ItemGroup>
</Project>
