<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dtos\"/>
    <None Remove="MappingProfiles\"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChangeDataCaptureHub.Model\ChangeDataCaptureHub.Model.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
  </ItemGroup>
</Project>
