<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Base\"/>
    <None Remove="Businesses\"/>
    <None Remove="Contracts\"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToDoListManager.Common\ToDoListManager.Common.csproj"/>
    <ProjectReference Include="..\ToDoListManager.DataAccess\ToDoListManager.DataAccess.csproj"/>
    <ProjectReference Include="..\ToDoListManager.ExternalServices\ToDoListManager.ExternalService.csproj"/>
  </ItemGroup>
</Project>
