<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e3dfdb9f-6df7-4d06-a886-5770b2c9d5ef</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <RootNamespace>ToDoListManager.Web</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'ToDoListManager.Web(Development)' "/>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'ToDoListManager.Web(Production)' "/>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'ToDoListManager.Web(Testing)' "/>

  <ItemGroup>
    <ProjectReference Include="..\ToDoListManager.Api\ToDoListManager.Api.csproj">
    </ProjectReference>
    <ProjectReference Include="..\ToDoListManager.ExternalServices\ToDoListManager.ExternalService.csproj">
    </ProjectReference>
    <ProjectReference Include="..\ToDoListManager.Services\ToDoListManager.Services.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ToDoListManager.IntegrationTest"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.MongoDB" Version="7.2.0" />
  </ItemGroup>
</Project>
