<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToDoListManager.Common\ToDoListManager.Common.csproj"/>
    <ProjectReference Include="..\ToDoListManager.Business\ToDoListManager.Business.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
  </ItemGroup>
</Project>
